name: Label Sync

on:
  push:
    branches: [main]
    paths: ['.github/labels.yml']
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sunday

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Sync Labels
        uses: EndBug/label-sync@v2
        with:
          config-file: .github/labels.yml
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-other-labels: false
